# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-07-05T15:45:00+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel, conint, constr


class ConfigStartup(BaseModel):
    allow_custom_startup_command: bool


class Parser(StrEnum):
    file = 'file'
    yaml = 'yaml'
    properties = 'properties'
    ini = 'ini'
    json = 'json'
    xml = 'xml'
    toml = 'toml'


class Limits(BaseModel):
    cpu: conint(ge=0)
    memory: conint(ge=0)
    memory_overhead: conint(ge=0)
    swap: conint(ge=-1)
    disk: conint(ge=0)
    io_weight: conint(ge=0, le=1000) | None = None


class FeatureLimits(BaseModel):
    allocations: conint(ge=0)
    databases: conint(ge=0)
    backups: conint(ge=0)
    schedules: conint(ge=0)


class AutoKill(BaseModel):
    enabled: bool
    seconds: conint(ge=0)


class AdminApiServerLimits(BaseModel):
    cpu: conint(ge=0)
    memory: conint(ge=0)
    memory_overhead: conint(ge=0)
    swap: conint(ge=-1)
    disk: conint(ge=0)
    io_weight: conint(ge=0, le=1000) | None = None


class AnnouncementType(StrEnum):
    info = 'info'
    success = 'success'
    warning = 'warning'
    error = 'error'


class ApiError(BaseModel):
    errors: list[str]


class Limits1(BaseModel):
    cpu: conint(ge=0)
    memory: conint(ge=0)
    swap: conint(ge=-1)
    disk: conint(ge=0)


class ApiServerFeatureLimits(BaseModel):
    allocations: conint(ge=0)
    databases: conint(ge=0)
    backups: conint(ge=0)
    schedules: conint(ge=0)


class AppContainerType(StrEnum):
    official = 'official'
    official_a_i_o = 'official_a_i_o'
    official_heavy = 'official_heavy'
    official_heavy_a_i_o = 'official_heavy_a_i_o'
    unknown = 'unknown'
    none = 'none'


class ArchiveFormat(StrEnum):
    tar = 'tar'
    tar_gz = 'tar_gz'
    tar_xz = 'tar_xz'
    tar_lzip = 'tar_lzip'
    tar_bz2 = 'tar_bz2'
    tar_lz4 = 'tar_lz4'
    tar_zstd = 'tar_zstd'
    zip = 'zip'
    seven_zip = 'seven_zip'


class AuthenticationType(StrEnum):
    password = 'password'
    public_key = 'public_key'


class BackupAdapter(StrEnum):
    wings = 'wings'
    s3 = 's3'
    ddup_bak = 'ddup-bak'
    btrfs = 'btrfs'
    zfs = 'zfs'
    restic = 'restic'
    proxmox_backup_server = 'proxmox-backup-server'
    kopia = 'kopia'


class PruneJob(BaseModel):
    cron: str = Field(..., examples=['0 0 0 * * *'])
    nodes: list[UUID]


class BackupDisk(StrEnum):
    local = 'local'
    s3 = 's3'
    ddup_bak = 'ddup-bak'
    btrfs = 'btrfs'
    zfs = 'zfs'
    restic = 'restic'
    proxmox_backup_server = 'proxmox-backup-server'
    kopia = 'kopia'


class Type(StrEnum):
    none = 'none'


class CaptchaProvider1(BaseModel):
    type: Type


class Type1(StrEnum):
    turnstile = 'turnstile'


class Type2(StrEnum):
    recaptcha = 'recaptcha'


class Type3(StrEnum):
    hcaptcha = 'hcaptcha'


class Type4(StrEnum):
    friendly_captcha = 'friendly_captcha'


class CompactString(RootModel[str]):
    root: str


class CompressionLevel(StrEnum):
    best_speed = 'best_speed'
    good_speed = 'good_speed'
    good_compression = 'good_compression'
    best_compression = 'best_compression'


class Type5(StrEnum):
    connection_string = 'connection_string'


class DatabaseCredentials1(BaseModel):
    connection_string: CompactString
    type: Type5


class Type6(StrEnum):
    details = 'details'


class DatabaseCredentials2(BaseModel):
    host: CompactString
    port: conint(ge=1)
    username: CompactString
    password: CompactString
    type: Type6


class DatabaseCredentials(RootModel[DatabaseCredentials1 | DatabaseCredentials2]):
    root: DatabaseCredentials1 | DatabaseCredentials2


class DatabaseType(StrEnum):
    mysql = 'mysql'
    postgres = 'postgres'
    mongodb = 'mongodb'


class DirectoryEntry(BaseModel):
    name: str
    mode: str
    mode_bits: str
    size: conint(ge=0)
    size_physical: conint(ge=0)
    editable: bool
    inner_editable: bool
    directory: bool
    file: bool
    symlink: bool
    mime: str
    created: AwareDatetime
    modified: AwareDatetime


class Primary(BaseModel):
    start_port: conint(ge=0)
    end_port: conint(ge=0)
    assign_to_variable: CompactString | None = None


class Type7(StrEnum):
    random = 'random'


class Mode(BaseModel):
    type: Type7


class Type8(StrEnum):
    range = 'range'


class Mode1(BaseModel):
    start_port: conint(ge=0)
    end_port: conint(ge=0)
    type: Type8


class Type9(StrEnum):
    add_primary = 'add_primary'


class Mode2(BaseModel):
    value: conint(ge=0)
    type: Type9


class Type10(StrEnum):
    subtract_primary = 'subtract_primary'


class Mode3(BaseModel):
    value: conint(ge=0)
    type: Type10


class Type11(StrEnum):
    multiply_primary = 'multiply_primary'


class Mode4(BaseModel):
    value: float
    type: Type11


class Type12(StrEnum):
    divide_primary = 'divide_primary'


class Mode5(BaseModel):
    value: float
    type: Type12


class AdditionalItem(BaseModel):
    mode: Mode | Mode1 | Mode2 | Mode3 | Mode4 | Mode5
    assign_to_variable: CompactString | None = None


class EggConfigAllocationsDeployment(BaseModel):
    dedicated: bool
    primary: Primary | None = None
    additional: list[AdditionalItem]


class EggConfigAllocationsUserSelfAssign(BaseModel):
    enabled: bool
    require_primary_allocation: bool
    start_port: conint(ge=0)
    end_port: conint(ge=0)


class ReplaceItem(BaseModel):
    match: CompactString
    insert_new: bool | None = None
    update_existing: bool | None = None
    if_value: CompactString | None = None
    replace_with: Any


class Files(BaseModel):
    create_new: bool | None = None
    parser: Parser
    replace: list[ReplaceItem]


class Startup(BaseModel):
    done: list[CompactString] | None = None
    strip_ansi: bool | None = None


class Stop(BaseModel):
    type: CompactString
    value: CompactString | None = None


class Config(BaseModel):
    files: dict[str, Files] | None = None
    startup: Startup | None = None
    stop: Stop | None = None


class Installation(BaseModel):
    container: CompactString
    entrypoint: CompactString
    content: str


class Scripts(BaseModel):
    installation: Installation


class Variable(BaseModel):
    name: CompactString
    name_translations: dict[str, CompactString] | None = None
    description: CompactString | None = None
    description_translations: dict[str, CompactString] | None = None
    order: int | None = None
    env_variable: CompactString
    default_value: constr(max_length=1024) | None = None
    user_viewable: bool
    user_editable: bool
    secret: bool | None = None
    rules: list[CompactString] | None = None


class ExportedNestEgg(BaseModel):
    uuid: UUID | None = None
    name: CompactString
    description: CompactString | None = None
    author: CompactString
    config: Config
    scripts: Scripts
    startup_commands: dict[str, CompactString]
    force_outgoing_ip: bool | None = None
    separate_port: bool | None = None
    features: list[CompactString] | None = None
    docker_images: dict[str, CompactString]
    file_denylist: list[CompactString] | None = None
    variables: list[Variable]


class Type13(StrEnum):
    no_update = 'no_update'


class ExtensionUpdateCheckResult1(BaseModel):
    type: Type13


class Type14(StrEnum):
    update_available = 'update_available'


class ExtensionUpdateCheckResult2(BaseModel):
    version: str
    latest_version: str
    changes: list[CompactString]
    type: Type14


class Type15(StrEnum):
    error = 'error'


class ExtensionUpdateCheckResult3(BaseModel):
    error: CompactString
    type: Type15


class ExtensionUpdateCheckResult(
    RootModel[
        ExtensionUpdateCheckResult1
        | ExtensionUpdateCheckResult2
        | ExtensionUpdateCheckResult3
    ]
):
    root: (
        ExtensionUpdateCheckResult1
        | ExtensionUpdateCheckResult2
        | ExtensionUpdateCheckResult3
    )


class Type16(StrEnum):
    none = 'none'


class MailMode1(BaseModel):
    type: Type16


class Type17(StrEnum):
    smtp = 'smtp'


class Type18(StrEnum):
    sendmail = 'sendmail'


class MailMode3(BaseModel):
    command: CompactString
    from_address: CompactString
    from_name: CompactString | None = None
    type: Type18


class Type19(StrEnum):
    filesystem = 'filesystem'


class MailMode4(BaseModel):
    path: CompactString
    from_address: CompactString
    from_name: CompactString | None = None
    type: Type19


class MassTransferAllocationMode(StrEnum):
    none = 'none'
    random_primary = 'random_primary'
    random_all = 'random_all'
    egg_config_deployment = 'egg_config_deployment'
    egg_config_self_assign_range = 'egg_config_self_assign_range'


class MetadataToml(BaseModel):
    package_name: str
    name: str
    panel_version: str
    license_text: str | None = None


class NtpOffset(BaseModel):
    offset_micros: int


class Type20(StrEnum):
    role = 'role'


class OAuthProviderMappingType1(BaseModel):
    role_uuid: UUID
    type: Type20


class Type21(StrEnum):
    server_subuser = 'server_subuser'


class OAuthProviderMappingType2(BaseModel):
    server_uuid: UUID
    permissions: list[CompactString]
    ignored_files: list[CompactString]
    type: Type21


class OAuthProviderMappingType(
    RootModel[OAuthProviderMappingType1 | OAuthProviderMappingType2]
):
    root: OAuthProviderMappingType1 | OAuthProviderMappingType2


class PendingExtension(BaseModel):
    metadata_toml: MetadataToml
    package_name: CompactString
    description: CompactString
    authors: list[CompactString]
    version: str


class Config1(BaseModel):
    file: CompactString
    create_new: bool | None = None
    parser: Parser
    replace: list[ReplaceItem]


class ProcessConfiguration(BaseModel):
    startup: Startup
    stop: Stop
    configs: list[Config1]


class RatelimitConfiguration(BaseModel):
    hits: conint(ge=0)
    window_seconds: conint(ge=0)


class State(StrEnum):
    offline = 'offline'
    starting = 'starting'
    stopping = 'stopping'
    running = 'running'


class Network(BaseModel):
    rx_bytes: conint(ge=0)
    rx_packets: conint(ge=0)
    tx_bytes: conint(ge=0)
    tx_packets: conint(ge=0)


class ResourceUsage(BaseModel):
    memory_bytes: conint(ge=0)
    memory_limit_bytes: conint(ge=0)
    disk_bytes: conint(ge=0)
    state: State
    network: Network
    cpu_absolute: float
    cpu_limit_absolute: conint(ge=0)
    uptime: conint(ge=0)


class Ssl(BaseModel):
    enabled: bool
    cert: str
    key: str


class Api(BaseModel):
    host: str
    port: conint(ge=0)
    ssl: Ssl
    redirects: dict[str, str]
    disable_openapi_docs: bool
    disable_remote_download: bool
    server_remote_download_limit: conint(ge=0)
    remote_download_blocked_cidrs: list[str]
    disable_directory_size: bool
    directory_entry_limit: conint(ge=0)
    send_offline_server_logs: bool
    file_search_threads: conint(ge=0)
    file_copy_threads: conint(ge=0)
    file_decompression_threads: conint(ge=0)
    file_compression_threads: conint(ge=0)
    upload_limit: conint(ge=0)
    max_jwt_uses: conint(ge=0)
    trusted_proxies: list[str]


class Rootless(BaseModel):
    enabled: bool
    container_uid: conint(ge=0)
    container_gid: conint(ge=0)


class User(BaseModel):
    rootless: Rootless
    uid: conint(ge=0)
    gid: conint(ge=0)


class Passwd(BaseModel):
    enabled: bool
    directory: str


class MachineId(BaseModel):
    enabled: bool


class DiskLimiterMode(StrEnum):
    none = 'none'
    btrfs_subvolume = 'btrfs_subvolume'
    zfs_dataset = 'zfs_dataset'
    xfs_quota = 'xfs_quota'
    fuse_quota = 'fuse_quota'


class Limits2(BaseModel):
    authentication_password_attempts: conint(ge=0)
    authentication_pubkey_attempts: conint(ge=0)
    authentication_cooldown: conint(ge=0)
    max_connections_per_user: conint(ge=0)
    max_channels_per_connection: conint(ge=0)
    max_handles_per_channel: conint(ge=0)
    max_handles_total: conint(ge=0)


class Cli(BaseModel):
    name: str


class Shell(BaseModel):
    enabled: bool
    cli: Cli


class Activity(BaseModel):
    log_logins: bool
    log_file_reads: bool


class Sftp(BaseModel):
    enabled: bool
    bind_address: str
    bind_port: conint(ge=0)
    read_only: bool
    key_algorithm: str
    disable_password_auth: bool
    directory_entry_limit: conint(ge=0)
    directory_entry_send_amount: conint(ge=0)
    limits: Limits2
    shell: Shell
    activity: Activity


class CrashDetection(BaseModel):
    enabled: bool
    detect_clean_exit_as_crash: bool
    timeout: conint(ge=0)


class FileHistory(BaseModel):
    enabled: bool
    zstd_level: int
    anchor_interval: conint(ge=0)
    keep_chains: conint(ge=0)
    file_size_cap: conint(ge=0)
    per_file_disk_budget: conint(ge=0)
    per_server_disk_budget: conint(ge=0)
    maintenance_interval: conint(ge=0)


class Mounting(BaseModel):
    enabled: bool
    path: str


class Wings(BaseModel):
    create_threads: conint(ge=0)
    restore_threads: conint(ge=0)
    archive_format: ArchiveFormat


class S3(BaseModel):
    create_threads: conint(ge=0)
    part_upload_timeout: conint(ge=0)
    retry_limit: conint(ge=0)


class CompressionFormat(StrEnum):
    none = 'none'
    deflate = 'deflate'
    gzip = 'gzip'
    brotli = 'brotli'


class DdupBak(BaseModel):
    create_threads: conint(ge=0)
    compression_format: CompressionFormat


class Restic(BaseModel):
    repository: str
    password_file: str
    retry_lock_seconds: conint(ge=0)
    environment: dict[str, str]


class Btrfs(BaseModel):
    restore_threads: conint(ge=0)
    create_read_only: bool


class Zfs(BaseModel):
    restore_threads: conint(ge=0)


class Backups(BaseModel):
    write_limit: conint(ge=0)
    read_limit: conint(ge=0)
    compression_level: CompressionLevel
    mounting: Mounting
    wings: Wings
    s3: S3
    ddup_bak: DdupBak
    restic: Restic
    btrfs: Btrfs
    zfs: Zfs


class Transfers(BaseModel):
    download_limit: conint(ge=0)


class System(BaseModel):
    root_directory: str
    log_directory: str
    vmount_directory: str
    data: str
    archive_directory: str
    backup_directory: str
    tmp_directory: str
    username: str
    timezone: str
    user: User
    passwd: Passwd
    machine_id: MachineId
    disk_check_concurrency: conint(ge=0)
    disk_check_interval: conint(ge=0)
    full_disk_check_every: conint(ge=0)
    disk_check_use_inotify: bool
    disk_limiter_mode: DiskLimiterMode
    activity_send_interval: conint(ge=0)
    activity_send_count: conint(ge=0)
    check_permissions_on_boot: bool
    check_permissions_on_boot_threads: conint(ge=0)
    websocket_log_count: conint(ge=0)
    sftp: Sftp
    crash_detection: CrashDetection
    file_history: FileHistory
    backups: Backups
    transfers: Transfers


class V4(BaseModel):
    subnet: str
    gateway: str


class V6(BaseModel):
    subnet: str
    gateway: str


class Interfaces(BaseModel):
    v4: V4
    v6: V6


class Network1(BaseModel):
    interface: str
    disable_interface_binding: bool
    dns: list[str]
    name: str
    ispn: bool
    driver: str
    mode: str
    is_internal: bool
    enable_icc: bool
    network_mtu: conint(ge=0)
    interfaces: Interfaces


class RegistryImageFetchCache(BaseModel):
    enabled: bool
    duration: conint(ge=0)


class InstallerLimits(BaseModel):
    timeout: conint(ge=0)
    memory: conint(ge=0)
    cpu: conint(ge=0)


class Overhead(BaseModel):
    override: bool
    default_multiplier: float
    multipliers: dict[str, float]


class LogConfig(BaseModel):
    type: str
    config: dict[str, str]


class Docker(BaseModel):
    socket: str
    server_name_in_container_name: bool
    delete_container_on_stop: bool
    network: Network1
    domainname: str
    registries: dict[str, Any]
    registry_image_fetch_cache: RegistryImageFetchCache
    tmpfs_size: conint(ge=0)
    container_pid_limit: conint(ge=0)
    container_apply_seccomp: bool
    installer_limits: InstallerLimits
    overhead: Overhead
    userns_mode: str
    log_config: LogConfig


class Throttles(BaseModel):
    enabled: bool
    lines: conint(ge=0)
    line_reset_interval: conint(ge=0)


class RemoteQuery(BaseModel):
    timeout: conint(ge=0)
    boot_servers_per_page: conint(ge=0)
    retry_limit: conint(ge=0)


class Response200(BaseModel):
    debug: bool
    app_name: str
    uuid: UUID
    token_id: str
    token: str
    api: Api
    system: System
    docker: Docker
    throttles: Throttles
    remote: str
    remote_headers: dict[str, str]
    remote_query: RemoteQuery
    allowed_mounts: list[str]
    allowed_origins: list[str]
    allow_cors_private_network: bool
    ignore_panel_config_updates: bool
    ignore_panel_wings_upgrades: bool


class Type22(StrEnum):
    route = 'route'


class RouteOrderItem1(BaseModel):
    path: CompactString
    type: Type22


class Type23(StrEnum):
    divider = 'divider'


class RouteOrderItem2(BaseModel):
    name: CompactString | None = None
    name_translations: dict[str, CompactString]
    type: Type23


class Type24(StrEnum):
    redirect = 'redirect'


class RouteOrderItem3(BaseModel):
    name: CompactString
    name_translations: dict[str, CompactString]
    destination: CompactString
    type: Type24


class RouteOrderItem(RootModel[RouteOrderItem1 | RouteOrderItem2 | RouteOrderItem3]):
    root: RouteOrderItem1 | RouteOrderItem2 | RouteOrderItem3


class Type25(StrEnum):
    sleep = 'sleep'


class ScheduleActionInner1(BaseModel):
    duration: conint(ge=1, le=86400)
    type: Type25


class Type26(StrEnum):
    ensure = 'ensure'


class Type27(StrEnum):
    format = 'format'


class Type28(StrEnum):
    match_regex = 'match_regex'


class Type29(StrEnum):
    wait_for_console_line = 'wait_for_console_line'


class Type30(StrEnum):
    send_power = 'send_power'


class Type31(StrEnum):
    send_command = 'send_command'


class Type32(StrEnum):
    create_backup = 'create_backup'


class Type33(StrEnum):
    create_directory = 'create_directory'


class Type34(StrEnum):
    write_file = 'write_file'


class Type35(StrEnum):
    copy_file = 'copy_file'


class Type36(StrEnum):
    delete_files = 'delete_files'


class File(BaseModel):
    from_: str = Field(..., alias='from')
    to: str


class Type37(StrEnum):
    rename_files = 'rename_files'


class Type38(StrEnum):
    compress_files = 'compress_files'


class Type39(StrEnum):
    decompress_file = 'decompress_file'


class Type40(StrEnum):
    update_startup_variable = 'update_startup_variable'


class Type41(StrEnum):
    update_startup_command = 'update_startup_command'


class Type42(StrEnum):
    update_startup_docker_image = 'update_startup_docker_image'


class Type43(StrEnum):
    none = 'none'


class ScheduleCondition1(BaseModel):
    type: Type43


class Type44(StrEnum):
    and_ = 'and'


class Type45(StrEnum):
    or_ = 'or'


class Type46(StrEnum):
    not_ = 'not'


class Type47(StrEnum):
    variable_exists = 'variable_exists'


class Type48(StrEnum):
    variable_equals = 'variable_equals'


class Type49(StrEnum):
    variable_contains = 'variable_contains'


class Type50(StrEnum):
    variable_starts_with = 'variable_starts_with'


class Type51(StrEnum):
    variable_ends_with = 'variable_ends_with'


class Type52(StrEnum):
    none = 'none'


class SchedulePreCondition1(BaseModel):
    type: Type52


class Type53(StrEnum):
    and_ = 'and'


class Type54(StrEnum):
    or_ = 'or'


class Type55(StrEnum):
    not_ = 'not'


class Type56(StrEnum):
    server_state = 'server_state'


class Type57(StrEnum):
    uptime = 'uptime'


class Type58(StrEnum):
    cpu_usage = 'cpu_usage'


class Type59(StrEnum):
    memory_usage = 'memory_usage'


class Type60(StrEnum):
    disk_usage = 'disk_usage'


class Type61(StrEnum):
    file_exists = 'file_exists'


class SchedulePreCondition10(BaseModel):
    file: constr(min_length=1, max_length=255)
    type: Type61


class ScheduleStatus(BaseModel):
    running: bool
    errors: dict[str, str]
    step: UUID | None = None


class Type62(StrEnum):
    cron = 'cron'


class ScheduleTrigger1(BaseModel):
    schedule: str = Field(..., examples=['* * * * * *'])
    type: Type62


class Type63(StrEnum):
    power_action = 'power_action'


class Type64(StrEnum):
    server_state = 'server_state'


class Type65(StrEnum):
    backup_status = 'backup_status'


class Type66(StrEnum):
    console_line = 'console_line'


class Type67(StrEnum):
    crash = 'crash'


class ScheduleTrigger6(BaseModel):
    type: Type67


class ScheduleVariable(BaseModel):
    variable: CompactString


class ServerAutoStartBehavior(StrEnum):
    always = 'always'
    unless_stopped = 'unless_stopped'
    never = 'never'


class ServerBackupStatus(StrEnum):
    starting = 'starting'
    finished = 'finished'
    failed = 'failed'


class Meta(BaseModel):
    name: str
    description: str


class Schedule(BaseModel):
    uuid: UUID
    triggers: Any
    condition: Any
    actions: list[Any]


class Default(BaseModel):
    ip: str
    port: conint(ge=0)


class Allocations(BaseModel):
    force_outgoing_ip: bool
    default: Default | None = None
    mappings: dict[str, list[conint(ge=0)]]


class Build(BaseModel):
    memory_limit: int
    overhead_memory: int
    swap: int
    io_weight: conint(ge=0) | None = None
    cpu_limit: int
    disk_space: conint(ge=0)
    threads: str | None = None
    oom_disabled: bool


class Mount(BaseModel):
    target: str
    source: str
    read_only: bool


class Egg(BaseModel):
    id: UUID
    file_denylist: list[str]


class Seccomp(BaseModel):
    remove_allowed: list[str]


class Container(BaseModel):
    image: str
    timezone: str | None = None
    hugepages_passthrough_enabled: bool
    kvm_passthrough_enabled: bool
    seccomp: Seccomp


class AutoStartBehavior(StrEnum):
    always = 'always'
    unless_stopped = 'unless_stopped'
    never = 'never'


class ServerConfiguration(BaseModel):
    uuid: UUID
    start_on_completion: bool | None = None
    meta: Meta
    suspended: bool
    invocation: str
    skip_egg_scripts: bool
    entrypoint: list[str] | None = None
    environment: dict[str, Any]
    labels: dict[str, str]
    backups: list[UUID]
    schedules: list[Schedule]
    allocations: Allocations
    build: Build
    mounts: list[Mount]
    egg: Egg
    container: Container
    auto_kill: AutoKill
    auto_start_behavior: AutoStartBehavior


class ServerPowerAction(StrEnum):
    start = 'start'
    stop = 'stop'
    restart = 'restart'
    kill = 'kill'


class ServerState(StrEnum):
    offline = 'offline'
    starting = 'starting'
    stopping = 'stopping'
    running = 'running'


class SshKeyProvider(StrEnum):
    github = 'github'
    gitlab = 'gitlab'
    launchpad = 'launchpad'


class StorageAsset(BaseModel):
    name: CompactString
    url: str
    size: conint(ge=0)
    is_directory: bool
    created: AwareDatetime


class Type68(StrEnum):
    filesystem = 'filesystem'


class StorageDriver1(BaseModel):
    path: CompactString
    type: Type68


class Type69(StrEnum):
    s3 = 's3'


class StorageDriver2(BaseModel):
    public_url: CompactString
    access_key: CompactString
    secret_key: CompactString
    bucket: CompactString
    region: CompactString
    endpoint: CompactString
    path_style: bool
    type: Type69


class StorageDriver(RootModel[StorageDriver1 | StorageDriver2]):
    root: StorageDriver1 | StorageDriver2


class TlsMode(StrEnum):
    none = 'none'
    start_tls = 'start_tls'
    implicit_tls = 'implicit_tls'


class TransferArchiveFormat(StrEnum):
    tar = 'tar'
    tar_gz = 'tar_gz'
    tar_xz = 'tar_xz'
    tar_lzip = 'tar_lzip'
    tar_bz2 = 'tar_bz2'
    tar_lz4 = 'tar_lz4'
    tar_zstd = 'tar_zstd'
    itaf = 'itaf'
    itaf_gz = 'itaf_gz'
    itaf_xz = 'itaf_xz'
    itaf_lzip = 'itaf_lzip'
    itaf_bz2 = 'itaf_bz2'
    itaf_lz4 = 'itaf_lz4'
    itaf_zstd = 'itaf_zstd'


class TransferProgress(BaseModel):
    archive_progress: conint(ge=0)
    network_progress: conint(ge=0)
    total: conint(ge=0)


class TwoFactorRequirement(StrEnum):
    admins = 'admins'
    all_users = 'all_users'
    none = 'none'


class UpdateInformation(BaseModel):
    panel_version: CompactString
    latest_panel_version: str
    latest_wings_version: str
    extensions: dict[str, ExtensionUpdateCheckResult]


class UserToastPosition(StrEnum):
    top_left = 'top_left'
    top_center = 'top_center'
    top_right = 'top_right'
    bottom_left = 'bottom_left'
    bottom_center = 'bottom_center'
    bottom_right = 'bottom_right'


class VersionHistoryEntry(BaseModel):
    version: CompactString
    timestamp: AwareDatetime


class AdminApiEggEggRepositoryEgg(RootModel[Any]):
    root: Any


class ApiEggConfiguration(RootModel[Any]):
    root: Any


class PermissionGroup(RootModel[Any]):
    root: Any


class SchedulePreConditionComparator(RootModel[Any]):
    root: Any


class ServerStatus(RootModel[Any]):
    root: Any


class AdminApiAnnouncement(BaseModel):
    uuid: UUID
    type: AnnouncementType
    enabled: bool
    enabled_start: AwareDatetime | None = None
    enabled_end: AwareDatetime | None = None
    dismissible: bool
    dismissible_end: AwareDatetime | None = None
    title: CompactString
    title_translations: dict[str, CompactString]
    content: CompactString
    content_translations: dict[str, CompactString]
    locations: list[UUID]
    nodes: list[UUID]
    backup_configurations: list[UUID]
    eggs: list[UUID]
    created: AwareDatetime


class AdminApiDatabaseHost(BaseModel):
    uuid: UUID
    name: CompactString
    deployment_enabled: bool
    maintenance_enabled: bool
    type: DatabaseType
    public_host: CompactString | None = None
    public_port: int | None = None
    credentials: DatabaseCredentials
    created: AwareDatetime


class ConfigAllocations(BaseModel):
    user_self_assign: EggConfigAllocationsUserSelfAssign | None = None
    deployment: EggConfigAllocationsDeployment | None = None


class ConfigRoutes(BaseModel):
    order: list[RouteOrderItem]


class AdminApiEggConfiguration(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    order: int
    eggs: list[UUID]
    config_allocations: ConfigAllocations | None = None
    config_startup: ConfigStartup | None = None
    config_routes: ConfigRoutes | None = None
    created: AwareDatetime


class AdminApiEggRepository(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    git_repository: CompactString
    last_synced: AwareDatetime | None = None
    created: AwareDatetime


class AdminApiEggRepositoryEgg(BaseModel):
    uuid: UUID
    path: str
    name: CompactString
    description: CompactString | None = None
    author: CompactString
    exported_egg: ExportedNestEgg


class AdminApiLocationDatabaseHost(BaseModel):
    database_host: AdminApiDatabaseHost
    created: AwareDatetime


class AdminApiMount(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    source: CompactString
    target: CompactString
    read_only: bool
    user_mountable: bool
    created: AwareDatetime


class AdminApiNest(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    author: CompactString
    created: AwareDatetime


class ConfigFile(BaseModel):
    file: CompactString
    create_new: bool | None = None
    parser: Parser
    replace: list[ReplaceItem]


class ConfigStartup1(BaseModel):
    done: list[CompactString] | None = None
    strip_ansi: bool | None = None


class ConfigStop(BaseModel):
    type: CompactString
    value: CompactString | None = None


class ConfigScript(BaseModel):
    container: CompactString
    entrypoint: CompactString
    content: str


class AdminApiNestEgg(BaseModel):
    uuid: UUID
    egg_repository_egg: AdminApiEggEggRepositoryEgg | None = None
    name: CompactString
    description: CompactString | None = None
    author: CompactString
    config_files: list[ConfigFile]
    config_startup: ConfigStartup1
    config_stop: ConfigStop
    config_script: ConfigScript
    startup_commands: dict[str, CompactString]
    force_outgoing_ip: bool
    separate_port: bool
    features: list[CompactString]
    docker_images: dict[str, CompactString]
    file_denylist: list[CompactString]
    created: AwareDatetime


class AdminApiNestEggMount(BaseModel):
    mount: AdminApiMount
    created: AwareDatetime


class AdminApiNestEggNestEggMount(BaseModel):
    nest: AdminApiNest
    nest_egg: AdminApiNestEgg
    created: AwareDatetime


class AdminApiNestEggVariable(BaseModel):
    uuid: UUID
    name: CompactString
    name_translations: dict[str, CompactString]
    description: CompactString | None = None
    description_translations: dict[str, CompactString]
    order: int
    env_variable: CompactString
    default_value: str | None = None
    user_viewable: bool
    user_editable: bool
    is_secret: bool
    rules: list[CompactString]
    created: AwareDatetime


class AdminApiNodeMount(BaseModel):
    mount: AdminApiMount
    created: AwareDatetime


class AdminApiOAuthProvider(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    client_id: CompactString
    client_secret: CompactString
    auth_url: str
    token_url: str
    info_url: str
    scopes: list[CompactString]
    identifier_path: str
    email_path: str | None = None
    username_path: str | None = None
    name_first_path: str | None = None
    name_last_path: str | None = None
    enabled: bool
    login_only: bool
    login_bypass_2fa: bool
    link_viewable: bool
    user_manageable: bool
    basic_auth: bool
    created: AwareDatetime


class AdminApiOAuthProviderMapping(BaseModel):
    uuid: UUID
    scopes: list[CompactString]
    mapping: OAuthProviderMappingType
    created: AwareDatetime


class AdminApiRole(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    admin_permissions: list[CompactString]
    server_permissions: list[CompactString]
    created: AwareDatetime


class AdminApiServerMount(BaseModel):
    mount: AdminApiMount
    created: AwareDatetime | None = None


class AdminApiUser(BaseModel):
    uuid: UUID
    external_id: CompactString | None = None
    username: CompactString
    role: AdminApiRole | None = None
    avatar: str | None = None
    email: CompactString
    name_first: CompactString
    name_last: CompactString
    admin: bool
    frozen: bool
    suspended: bool
    totp_enabled: bool
    totp_last_used: AwareDatetime | None = None
    require_two_factor: bool
    language: CompactString
    toast_position: UserToastPosition
    start_on_grouped_servers: bool
    has_password: bool
    created: AwareDatetime


class AdminApiUserOAuthLink(BaseModel):
    uuid: UUID
    user: AdminApiUser
    identifier: CompactString
    last_used: AwareDatetime | None = None
    created: AwareDatetime


class ApiAnnouncement(BaseModel):
    uuid: UUID
    type: AnnouncementType
    dismissible: bool
    dismissible_end: AwareDatetime | None = None
    title: CompactString
    title_translations: dict[str, CompactString]
    content: CompactString
    content_translations: dict[str, CompactString]


class ApiDatabaseHost(BaseModel):
    uuid: UUID
    name: CompactString
    maintenance_enabled: bool
    type: DatabaseType
    host: CompactString
    port: int


class ApiFullUser(BaseModel):
    uuid: UUID
    username: CompactString
    role: AdminApiRole | None = None
    avatar: str | None = None
    email: CompactString
    name_first: CompactString
    name_last: CompactString
    admin: bool
    frozen: bool
    suspended: bool
    totp_enabled: bool
    totp_last_used: AwareDatetime | None = None
    require_two_factor: bool
    language: CompactString
    toast_position: UserToastPosition
    start_on_grouped_servers: bool
    has_password: bool
    created: AwareDatetime


class ApiNestEgg(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    startup_commands: dict[str, CompactString]
    separate_port: bool
    features: list[CompactString]
    docker_images: dict[str, CompactString]
    created: AwareDatetime


class ApiOAuthProvider(BaseModel):
    uuid: UUID
    name: CompactString
    link_viewable: bool
    user_manageable: bool


class ApiServerAllocation(BaseModel):
    uuid: UUID
    ip: CompactString
    ip_alias: CompactString | None = None
    port: int
    notes: CompactString | None = None
    is_primary: bool
    created: AwareDatetime


class ApiServerBackup(BaseModel):
    uuid: UUID
    name: CompactString
    ignored_files: list[CompactString]
    is_successful: bool
    is_locked: bool
    is_browsable: bool
    is_streaming: bool
    checksum: CompactString | None = None
    bytes: int
    files: int
    metadata: Any
    completed: AwareDatetime | None = None
    created: AwareDatetime


class ApiServerDatabase(BaseModel):
    uuid: UUID
    type: DatabaseType
    host: CompactString
    port: int
    name: CompactString
    is_locked: bool
    username: CompactString
    password: CompactString | None = None
    created: AwareDatetime


class ApiServerMount(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    target: CompactString
    read_only: bool
    created: AwareDatetime | None = None


class ApiServerVariable(BaseModel):
    name: CompactString
    name_translations: dict[str, CompactString]
    description: CompactString | None = None
    description_translations: dict[str, CompactString]
    env_variable: CompactString
    default_value: str | None = None
    value: str
    is_editable: bool
    is_secret: bool
    rules: list[CompactString]
    created: AwareDatetime


class ApiUser(BaseModel):
    uuid: UUID
    username: CompactString
    avatar: str | None = None
    totp_enabled: bool
    created: AwareDatetime


class ApiUserActivity(BaseModel):
    impersonator: ApiUser | None = None
    event: CompactString
    ip: CompactString | None = None
    data: Any
    is_api: bool
    created: AwareDatetime


class ApiUserApiKey(BaseModel):
    uuid: UUID
    name: CompactString
    key_start: CompactString
    allowed_ips: list[str]
    user_permissions: list[CompactString]
    admin_permissions: list[CompactString]
    server_permissions: list[CompactString]
    last_used: AwareDatetime | None = None
    expires: AwareDatetime | None = None
    created: AwareDatetime


class ApiUserCommandSnippet(BaseModel):
    uuid: UUID
    name: CompactString
    eggs: list[UUID]
    command: CompactString
    created: AwareDatetime


class ApiUserOAuthLink(BaseModel):
    uuid: UUID
    oauth_provider: ApiOAuthProvider
    identifier: CompactString
    last_used: AwareDatetime | None = None
    created: AwareDatetime


class ApiUserSecurityKey(BaseModel):
    uuid: UUID
    name: CompactString
    credential_id: str
    last_used: AwareDatetime | None = None
    created: AwareDatetime


class ApiUserServerGroup(BaseModel):
    uuid: UUID
    name: CompactString
    order: int
    server_order: list[UUID]
    created: AwareDatetime


class ApiUserSession(BaseModel):
    uuid: UUID
    ip: CompactString
    user_agent: CompactString
    is_using: bool
    last_used: AwareDatetime
    created: AwareDatetime


class ApiUserSshKey(BaseModel):
    uuid: UUID
    name: CompactString
    fingerprint: CompactString
    created: AwareDatetime


class BackupConfigKopia(BaseModel):
    url: CompactString
    username: CompactString
    password: CompactString
    fingerprint: CompactString
    tags: dict[str, CompactString]


class BackupConfigsPbs(BaseModel):
    url: CompactString
    datastore: CompactString
    namespace: CompactString | None = None
    token_id: CompactString
    token_secret: CompactString
    fingerprint: CompactString
    backup_id_prefix: CompactString | None = None


class BackupConfigsRestic(BaseModel):
    repository: CompactString
    retry_lock_seconds: conint(ge=0)
    environment: dict[str, CompactString]
    prune_jobs: list[PruneJob] | None = Field(None, max_length=50)


class BackupConfigsS3(BaseModel):
    access_key: CompactString
    secret_key: CompactString
    bucket: CompactString
    region: CompactString
    endpoint: CompactString
    path_style: bool
    part_size: conint(ge=0)


class CaptchaProvider2(BaseModel):
    site_key: CompactString
    secret_key: CompactString
    type: Type1


class CaptchaProvider3(BaseModel):
    v3: bool
    site_key: CompactString
    secret_key: CompactString
    type: Type2


class CaptchaProvider4(BaseModel):
    site_key: CompactString
    secret_key: CompactString
    type: Type3


class CaptchaProvider5(BaseModel):
    site_key: CompactString
    api_key: CompactString
    type: Type4


class CaptchaProvider(
    RootModel[
        CaptchaProvider1
        | CaptchaProvider2
        | CaptchaProvider3
        | CaptchaProvider4
        | CaptchaProvider5
    ]
):
    root: (
        CaptchaProvider1
        | CaptchaProvider2
        | CaptchaProvider3
        | CaptchaProvider4
        | CaptchaProvider5
    )


class ConstructedExtension(BaseModel):
    metadata_toml: MetadataToml
    package_name: str
    description: str
    authors: list[str]
    version: str


class MailMode2(BaseModel):
    host: CompactString
    port: conint(ge=0)
    username: CompactString | None = None
    password: CompactString | None = None
    tls_mode: TlsMode
    skip_cert_validation: bool | None = None
    from_address: CompactString
    from_name: CompactString | None = None
    type: Type17


class MailMode(RootModel[MailMode1 | MailMode2 | MailMode3 | MailMode4]):
    root: MailMode1 | MailMode2 | MailMode3 | MailMode4


class PermissionMap(RootModel[dict[str, PermissionGroup]]):
    root: dict[str, PermissionGroup]


class RemoteApiServer(BaseModel):
    settings: ServerConfiguration
    process_configuration: ProcessConfiguration


class ResponseVersionHistory(BaseModel):
    panel: list[VersionHistoryEntry]
    extensions: dict[str, list[VersionHistoryEntry]]


class Revision(BaseModel):
    id: int
    user: ApiUser | None = None
    size: conint(ge=0)
    is_snapshot: bool
    created: AwareDatetime


class ScheduleActionInner3(BaseModel):
    format: constr(min_length=1, max_length=2048)
    output_into: ScheduleVariable
    type: Type27


class ScheduleActionInner6(BaseModel):
    ignore_failure: bool
    action: ServerPowerAction
    type: Type30


class ScheduleCondition5(BaseModel):
    variable: ScheduleVariable
    type: Type47


class ScheduleDynamicParameter(RootModel[CompactString | ScheduleVariable]):
    root: CompactString | ScheduleVariable


class SchedulePreCondition5(BaseModel):
    state: ServerState
    type: Type56


class SchedulePreCondition6(BaseModel):
    comparator: SchedulePreConditionComparator
    value: conint(ge=0)
    type: Type57


class SchedulePreCondition7(BaseModel):
    comparator: SchedulePreConditionComparator
    value: float
    type: Type58


class SchedulePreCondition8(BaseModel):
    comparator: SchedulePreConditionComparator
    value: conint(ge=0)
    type: Type59


class SchedulePreCondition9(BaseModel):
    comparator: SchedulePreConditionComparator
    value: conint(ge=0)
    type: Type60


class ScheduleTrigger2(BaseModel):
    action: ServerPowerAction
    type: Type63


class ScheduleTrigger3(BaseModel):
    state: ServerState
    type: Type64


class ScheduleTrigger4(BaseModel):
    status: ServerBackupStatus
    type: Type65


class ScheduleTrigger5(BaseModel):
    contains: CompactString
    case_insensitive: bool | None = None
    output_into: ScheduleVariable | None = None
    type: Type66


class ScheduleTrigger(
    RootModel[
        ScheduleTrigger1
        | ScheduleTrigger2
        | ScheduleTrigger3
        | ScheduleTrigger4
        | ScheduleTrigger5
        | ScheduleTrigger6
    ]
):
    root: (
        ScheduleTrigger1
        | ScheduleTrigger2
        | ScheduleTrigger3
        | ScheduleTrigger4
        | ScheduleTrigger5
        | ScheduleTrigger6
    )


class AdminApiAdminActivity(BaseModel):
    user: ApiUser | None = None
    impersonator: ApiUser | None = None
    event: CompactString
    ip: CompactString | None = None
    data: Any
    is_api: bool
    created: AwareDatetime


class ApiServer(BaseModel):
    uuid: UUID
    uuid_short: CompactString
    allocation: ApiServerAllocation | None = None
    egg: ApiNestEgg
    egg_configuration: ApiEggConfiguration
    status: ServerStatus | None = None
    is_owner: bool
    is_suspended: bool
    is_transferring: bool
    permissions: list[CompactString]
    location_uuid: UUID
    location_name: CompactString
    location_flag: CompactString | None = None
    node_uuid: UUID
    node_name: CompactString
    node_maintenance_enabled: bool
    sftp_host: CompactString
    sftp_port: int
    name: CompactString
    description: CompactString | None = None
    limits: Limits1
    feature_limits: FeatureLimits = Field(..., title='ApiServerFeatureLimits')
    startup: CompactString
    image: CompactString
    auto_kill: AutoKill
    auto_start_behavior: ServerAutoStartBehavior
    timezone: CompactString | None = None
    created: AwareDatetime


class ApiServerActivity(BaseModel):
    user: ApiUser | None = None
    impersonator: ApiUser | None = None
    event: CompactString
    ip: CompactString | None = None
    data: Any
    is_api: bool
    is_schedule: bool
    created: AwareDatetime


class ApiServerSubuser(BaseModel):
    user: ApiUser
    permissions: list[CompactString]
    ignored_files: list[CompactString]
    created: AwareDatetime


class BackupConfigs(BaseModel):
    s3: BackupConfigsS3 | None = None
    restic: BackupConfigsRestic | None = None
    pbs: BackupConfigsPbs | None = None
    kopia: BackupConfigKopia | None = None


class ScheduleActionInner4(BaseModel):
    input: ScheduleDynamicParameter
    regex: str
    output_into: list[ScheduleVariable | None]
    type: Type28


class ScheduleActionInner5(BaseModel):
    ignore_failure: bool
    contains: ScheduleDynamicParameter
    case_insensitive: bool | None = None
    timeout: conint(ge=1, le=86400)
    output_into: ScheduleVariable | None = None
    type: Type29


class ScheduleActionInner7(BaseModel):
    ignore_failure: bool
    command: ScheduleDynamicParameter
    type: Type31


class ScheduleActionInner8(BaseModel):
    ignore_failure: bool
    foreground: bool
    name: ScheduleDynamicParameter | None = None
    ignored_files: list[CompactString]
    type: Type32


class ScheduleActionInner9(BaseModel):
    ignore_failure: bool
    root: ScheduleDynamicParameter
    name: ScheduleDynamicParameter
    type: Type33


class ScheduleActionInner10(BaseModel):
    ignore_failure: bool
    append: bool
    file: ScheduleDynamicParameter
    content: ScheduleDynamicParameter
    type: Type34


class ScheduleActionInner11(BaseModel):
    ignore_failure: bool
    foreground: bool
    file: ScheduleDynamicParameter
    destination: ScheduleDynamicParameter
    type: Type35


class ScheduleActionInner12(BaseModel):
    root: ScheduleDynamicParameter
    files: list[CompactString]
    type: Type36


class ScheduleActionInner13(BaseModel):
    root: ScheduleDynamicParameter
    files: list[File]
    type: Type37


class ScheduleActionInner14(BaseModel):
    ignore_failure: bool
    foreground: bool
    root: ScheduleDynamicParameter
    files: list[CompactString]
    format: ArchiveFormat
    name: ScheduleDynamicParameter
    type: Type38


class ScheduleActionInner15(BaseModel):
    ignore_failure: bool
    foreground: bool
    root: ScheduleDynamicParameter
    file: ScheduleDynamicParameter
    type: Type39


class ScheduleActionInner16(BaseModel):
    ignore_failure: bool
    env_variable: ScheduleDynamicParameter
    value: ScheduleDynamicParameter
    type: Type40


class ScheduleActionInner17(BaseModel):
    ignore_failure: bool
    command: ScheduleDynamicParameter
    type: Type41


class ScheduleActionInner18(BaseModel):
    ignore_failure: bool
    image: ScheduleDynamicParameter
    type: Type42


class ScheduleCondition6(BaseModel):
    variable: ScheduleVariable
    equals: ScheduleDynamicParameter
    type: Type48


class ScheduleCondition7(BaseModel):
    variable: ScheduleVariable
    contains: ScheduleDynamicParameter
    type: Type49


class ScheduleCondition8(BaseModel):
    variable: ScheduleVariable
    starts_with: ScheduleDynamicParameter
    type: Type50


class ScheduleCondition9(BaseModel):
    variable: ScheduleVariable
    ends_with: ScheduleDynamicParameter
    type: Type51


class AdminApiBackupConfiguration(BaseModel):
    uuid: UUID
    name: CompactString
    description: CompactString | None = None
    maintenance_enabled: bool
    shared: bool
    backup_disk: BackupDisk
    backup_configs: BackupConfigs
    created: AwareDatetime


class AdminApiLocation(BaseModel):
    uuid: UUID
    backup_configuration: AdminApiBackupConfiguration | None = None
    name: CompactString
    description: CompactString | None = None
    flag: CompactString | None = None
    created: AwareDatetime


class AdminApiNode(BaseModel):
    uuid: UUID
    location: AdminApiLocation
    backup_configuration: AdminApiBackupConfiguration | None = None
    name: CompactString
    description: CompactString | None = None
    deployment_enabled: bool
    maintenance_enabled: bool
    public_url: AnyUrl | None = None
    url: AnyUrl
    sftp_host: CompactString | None = None
    sftp_port: int
    memory: int
    disk: int
    created: AwareDatetime


class AdminApiNodeNodeMount(BaseModel):
    node: AdminApiNode
    created: AwareDatetime


class AdminApiServer(BaseModel):
    uuid: UUID
    uuid_short: CompactString
    external_id: CompactString | None = None
    allocation: ApiServerAllocation | None = None
    node: AdminApiNode
    owner: ApiFullUser
    egg: AdminApiNestEgg
    nest: AdminApiNest
    backup_configuration: AdminApiBackupConfiguration | None = None
    status: ServerStatus | None = None
    is_suspended: bool
    is_transferring: bool
    name: CompactString
    description: CompactString | None = None
    limits: Limits
    pinned_cpus: list[int]
    feature_limits: FeatureLimits = Field(..., title='ApiServerFeatureLimits')
    startup: CompactString
    image: CompactString
    auto_kill: AutoKill
    auto_start_behavior: ServerAutoStartBehavior
    timezone: CompactString | None = None
    hugepages_passthrough_enabled: bool
    kvm_passthrough_enabled: bool
    created: AwareDatetime


class AdminApiServerBackup(BaseModel):
    uuid: UUID
    server: AdminApiServer | None = None
    name: CompactString
    ignored_files: list[CompactString]
    is_successful: bool
    is_locked: bool
    is_browsable: bool
    is_streaming: bool
    is_shared: bool
    checksum: CompactString | None = None
    bytes: int
    files: int
    metadata: Any
    completed: AwareDatetime | None = None
    created: AwareDatetime


class AdminApiServerDatabase(BaseModel):
    uuid: UUID
    server: AdminApiServer
    type: DatabaseType
    host: CompactString
    port: int
    name: CompactString
    is_locked: bool
    username: CompactString
    password: CompactString
    created: AwareDatetime


class AdminApiServerServerMount(BaseModel):
    server: AdminApiServer
    created: AwareDatetime


class ResponseNode(BaseModel):
    version: CompactString
    node: AdminApiNode


class AdminApiNodeAllocation(BaseModel):
    uuid: UUID
    server: AdminApiServer | None = None
    ip: CompactString
    ip_alias: CompactString | None = None
    port: int
    created: AwareDatetime


class AdminApiNodeServerBackup(BaseModel):
    uuid: UUID
    server: AdminApiServer | None = None
    node: AdminApiNode
    name: CompactString
    ignored_files: list[CompactString]
    is_successful: bool
    is_locked: bool
    is_browsable: bool
    is_streaming: bool
    is_shared: bool
    checksum: CompactString | None = None
    bytes: int
    files: int
    metadata: Any
    completed: AwareDatetime | None = None
    created: AwareDatetime


class ApiServerSchedule(BaseModel):
    uuid: UUID
    name: CompactString
    enabled: bool
    triggers: list[ScheduleTrigger]
    condition: SchedulePreCondition
    last_run: AwareDatetime | None = None
    last_failure: AwareDatetime | None = None
    created: AwareDatetime


class ApiServerScheduleStep(BaseModel):
    uuid: UUID
    action: ScheduleActionInner
    order: int
    error: CompactString | None = None
    created: AwareDatetime


class ExportedServerSchedule(BaseModel):
    name: CompactString
    enabled: bool
    triggers: list[ScheduleTrigger]
    condition: SchedulePreCondition
    steps: list[ExportedServerScheduleStep]


class ExportedServerScheduleStep(BaseModel):
    action: ScheduleActionInner
    order: int


class ScheduleActionInner2(BaseModel):
    condition: ScheduleCondition
    type: Type26


class ScheduleCondition2(BaseModel):
    conditions: list[ScheduleCondition]
    type: Type44


class ScheduleCondition3(BaseModel):
    conditions: list[ScheduleCondition]
    type: Type45


class ScheduleCondition4(BaseModel):
    condition: ScheduleCondition
    type: Type46


class SchedulePreCondition2(BaseModel):
    conditions: list[SchedulePreCondition]
    type: Type53


class SchedulePreCondition3(BaseModel):
    conditions: list[SchedulePreCondition]
    type: Type54


class SchedulePreCondition4(BaseModel):
    condition: SchedulePreCondition
    type: Type55


class ScheduleActionInner(
    RootModel[
        ScheduleActionInner1
        | ScheduleActionInner2
        | ScheduleActionInner3
        | ScheduleActionInner4
        | ScheduleActionInner5
        | ScheduleActionInner6
        | ScheduleActionInner7
        | ScheduleActionInner8
        | ScheduleActionInner9
        | ScheduleActionInner10
        | ScheduleActionInner11
        | ScheduleActionInner12
        | ScheduleActionInner13
        | ScheduleActionInner14
        | ScheduleActionInner15
        | ScheduleActionInner16
        | ScheduleActionInner17
        | ScheduleActionInner18
    ]
):
    root: (
        ScheduleActionInner1
        | ScheduleActionInner2
        | ScheduleActionInner3
        | ScheduleActionInner4
        | ScheduleActionInner5
        | ScheduleActionInner6
        | ScheduleActionInner7
        | ScheduleActionInner8
        | ScheduleActionInner9
        | ScheduleActionInner10
        | ScheduleActionInner11
        | ScheduleActionInner12
        | ScheduleActionInner13
        | ScheduleActionInner14
        | ScheduleActionInner15
        | ScheduleActionInner16
        | ScheduleActionInner17
        | ScheduleActionInner18
    )


class ScheduleCondition(
    RootModel[
        ScheduleCondition1
        | ScheduleCondition2
        | ScheduleCondition3
        | ScheduleCondition4
        | ScheduleCondition5
        | ScheduleCondition6
        | ScheduleCondition7
        | ScheduleCondition8
        | ScheduleCondition9
    ]
):
    root: (
        ScheduleCondition1
        | ScheduleCondition2
        | ScheduleCondition3
        | ScheduleCondition4
        | ScheduleCondition5
        | ScheduleCondition6
        | ScheduleCondition7
        | ScheduleCondition8
        | ScheduleCondition9
    )


class SchedulePreCondition(
    RootModel[
        SchedulePreCondition1
        | SchedulePreCondition2
        | SchedulePreCondition3
        | SchedulePreCondition4
        | SchedulePreCondition5
        | SchedulePreCondition6
        | SchedulePreCondition7
        | SchedulePreCondition8
        | SchedulePreCondition9
        | SchedulePreCondition10
    ]
):
    root: (
        SchedulePreCondition1
        | SchedulePreCondition2
        | SchedulePreCondition3
        | SchedulePreCondition4
        | SchedulePreCondition5
        | SchedulePreCondition6
        | SchedulePreCondition7
        | SchedulePreCondition8
        | SchedulePreCondition9
        | SchedulePreCondition10
    )


ApiServerSchedule.model_rebuild()
ApiServerScheduleStep.model_rebuild()
ExportedServerSchedule.model_rebuild()
ExportedServerScheduleStep.model_rebuild()
ScheduleActionInner2.model_rebuild()
ScheduleCondition2.model_rebuild()
ScheduleCondition3.model_rebuild()
ScheduleCondition4.model_rebuild()
SchedulePreCondition2.model_rebuild()
SchedulePreCondition3.model_rebuild()
SchedulePreCondition4.model_rebuild()
